AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront resources for static website hosting

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
    
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: The deployment environment

  WebsiteBucketName:
    Type: String
    Description: Name of the S3 bucket for website files
  
  ApiEndpoint:
    Type: String
    Description: API Gateway endpoint URL (format: https://api-id.execute-api.region.amazonaws.com/stage/resource)

Resources:
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub ${AWS::StackName} OAI

  # Bucket Policy for CloudFront access
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucketName
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${WebsiteBucketName}/*
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub ${WebsiteBucketName}.s3.amazonaws.com
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
          - DomainName: !Select [2, !Split ["/", !Ref ApiEndpoint]]
            Id: ApiOrigin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        CacheBehaviors:
          - PathPattern: /api/*
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            TargetOriginId: ApiOrigin
            ForwardedValues:
              QueryString: true
              Headers:
                - Authorization
                - Content-Type
              Cookies:
                Forward: all
            ViewerProtocolPolicy: https-only
            MinTTL: 0
            DefaultTTL: 0
            MaxTTL: 0
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  WebsiteUrl:
    Description: "CloudFront distribution URL for the website"
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${ProjectName}-${Environment}-WebsiteUrl"
      
  DistributionId:
    Description: "CloudFront distribution ID"
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "${ProjectName}-${Environment}-DistributionId"
      
  CloudFrontOAI:
    Description: "CloudFront Origin Access Identity"
    Value: !Ref CloudFrontOAI
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CloudFrontOAI"
      
  CloudFrontDistributionDomainName:
    Description: "CloudFront Distribution Domain Name"
    Value: !GetAtt CloudFrontDistribution.DomainName
    
  ApiUrl:
    Description: "CloudFront URL for API access"
    Value: !Sub "https://${CloudFrontDistribution.DomainName}/api"
    Export:
      Name: !Sub "${ProjectName}-${Environment}-ApiUrl"