AWSTemplateFormatVersion: '2010-09-09'
Description: S3 resources for static website hosting

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
    
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: The deployment environment

Resources:
  # S3 Bucket for static assets
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-website-bucket
        - Key: Environment
          Value: !Ref Environment

Outputs:
  WebsiteBucketName:
    Description: S3 Bucket for website content
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub "${ProjectName}-${Environment}-WebsiteBucketName"