AWSTemplateFormatVersion: '2010-09-09'
Description: Main CloudFormation template that orchestrates nested stacks for a web application

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: The deployment environment
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID of the existing company VPC
  
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of existing subnet IDs for deployment (minimum 2 recommended)

Resources:
  # Security Groups Stack
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/security-groups.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !Ref VpcId
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # S3 and CloudFront Stack
  StaticWebsiteStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/static-website.yaml
      Parameters:
        Environment: !Ref Environment
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Load Balancer Stack
  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/load-balancer.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !Ref VpcId
        SubnetIds: !Join [',', !Ref SubnetIds]
        WebServerSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.WebServerSecurityGroupId
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  WebServerSecurityGroupId:
    Description: Security Group ID for web servers
    Value: !GetAtt SecurityGroupsStack.Outputs.WebServerSecurityGroupId
    Export:
      Name: !Sub ${AWS::StackName}-WebServerSecurityGroupId

  WebsiteBucketName:
    Description: S3 Bucket for website content
    Value: !GetAtt StaticWebsiteStack.Outputs.WebsiteBucketName
    Export:
      Name: !Sub ${AWS::StackName}-WebsiteBucketName

  CloudFrontDistributionDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt StaticWebsiteStack.Outputs.CloudFrontDistributionDomainName
    Export:
      Name: !Sub ${AWS::StackName}-CloudFrontDomainName
      
  LoadBalancerDnsName:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt LoadBalancerStack.Outputs.LoadBalancerDnsName
    Export:
      Name: !Sub ${AWS::StackName}-LoadBalancerDnsName